import sqlite3

def seedMerchants():
    conn = sqlite3.connect('merchants.db')
    c = conn.cursor()
    #Create table
    c.execute("INSERT INTO merchants VALUES (Chipotle, Dining)")
    c.execute("INSERT INTO merchants VALUES (Smiths, Grocery)")
    c.execute("INSERT INTO merchants VALUES (Dell, Shopping)")
    c.execute("INSERT INTO merchants VALUES (Delta Airlines, Travel)")
    c.execute("INSERT INTO merchants VALUES (Burger King, Dining)")
    c.execute("INSERT INTO merchants VALUES (McDonalds, Dining)")
    c.execute("INSERT INTO merchants VALUES (Hydroflask, Shopping)")
    c.execute("INSERT INTO merchants VALUES (Chinatown Supermarket, Grocery)")
    c.execute("INSERT INTO merchants VALUES (Starbucks, Coffee_Shops)")
    c.execute("INSERT INTO merchants VALUES (Shell_Gas, Gas)")
    c.execute("INSERT INTO merchants VALUES (Chevron, Gas)")
    c.execute("INSERT INTO merchants VALUES (Home_Depot, Home_Improvement)")
    c.execute("INSERT INTO merchants VALUES (Roxys, Dining)")
    c.execute("INSERT INTO merchants VALUES (Salt_and_Straw, Dining)")
    c.execute("INSERT INTO merchants VALUES (Apple_Inc, Shopping)")
    c.execute("INSERT INTO merchants VALUES (Whole_Foods, Grocery)")
    c.execute("INSERT INTO merchants VALUES (Trader_Joes, Grocery)")
    c.execute("INSERT INTO merchants VALUES (Hilton, Hotels)")
    c.execute("INSERT INTO merchants VALUES (Mariott, Hotels)")
    conn.commit()
    conn.close()